### ISSUE TITLE
Any fix please 

### ISSUE THREAD

**Issue by Gamerns10s** [FortniteFevers/Fortnite-Shop-Bot#6]
![IMG_20240930_125511](https://github.com/user-attachments/assets/3bf92103-435e-41a7-aebf-2d362c580bd9)

**Comment by radarhere** [comment]
This error was fixed by installing Pillow dependencies, `apt-get install freetype libjpeg-turbo zlib`, and then re-installing Pillow. See https://github.com/python-pillow/Pillow/issues/8433 for the discussion about that.

**Comment by FortniteFevers** [comment]
Fully fixed! Check out the dev branch.
